---
resources:

# Git repository for the application source, dev branch
- name: cicd-repo-dev
  type: git
  source:
    uri: https://github.com/navin-kumar-srnk/cicdtest.git
    branch: main

jobs:
  - name: build-react
    public: true
    plan: 
      - get: cicd-repo-dev
        trigger: true
      - task: install-dep
        config:  
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: node, tag: lts}
            params:
              application_name: cicdtest
              application_repo: cicd-repo-dev
          inputs:
            - name:  cicd-repo-dev

          run:
            path: cicd-repo-dev/ci/installdep.sh

    
