---
resources:

# Git repository for the application source, dev branch
- name: quiz-repo-dev
  type: git
  source:
    uri: https://github.com/gigo6000/quiz.git
    branch: master

jobs:
  - name: build-react
    public: true
    plan: 
      - get: quiz-repo-dev
        trigger: true
      - task: install-dep
        config:  
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: node, tag: lts}

          inputs:
            - name:  quiz-repo-dev

          run:
            path: /bin/sh
            args:
              - -cx
              - |
                cd quiz-repo-dev
                npm i
                npm run build

    
